"use strict";
const React = require('react');
const react_router_1 = require('react-router');
const location_1 = require("../../components/location");
const nav_1 = require("./nav");
class MemberPage extends React.Component {
    render() {
        return (React.createElement("div", {className: "main2"}, 
            React.createElement(location_1.default, null), 
            React.createElement(nav_1.default, null), 
            React.createElement("div", {className: "m2fm_stop"}, 
                React.createElement("span", {className: "m2fm_ss1"}, "姓名："), 
                React.createElement("input", {type: "text", name: "", className: "m2fm_int m2fm_int6"}), 
                React.createElement("span", {className: "m2fm_ss1"}, "变动时间："), 
                React.createElement("input", {type: "text", name: "", className: "m2fm_int m2fm_int2", placeholder: "2016-01-20"}), 
                React.createElement("span", {className: "m2fm_ss1 m2fm_ss2"}, "至"), 
                React.createElement("input", {type: "text", name: "", className: "m2fm_int m2fm_int2", placeholder: "2016-01-20"}), 
                React.createElement("input", {type: "submit", name: "", className: "m2submit", value: ""}), 
                React.createElement(react_router_1.Link, {to: "/member/add", className: "m2addBtn"}, 
                    React.createElement("img", {src: "/assets/images/m2btn.jpg", width: "76", height: "32"})
                )), 
            React.createElement("div", {className: "m2fm_tabBox m2fm_tabBox2"}, 
                React.createElement("table", {width: "100%"}, 
                    React.createElement("tr", {className: "m2th"}, 
                        React.createElement("td", {width: "4%"}, 
                            React.createElement("input", {className: "lay-rad", name: "", type: "checkbox", value: ""})
                        ), 
                        React.createElement("td", {width: "9%"}, "姓名"), 
                        React.createElement("td", {width: "9%"}, "性别"), 
                        React.createElement("td", {width: "16%"}, "所属组织"), 
                        React.createElement("td", {width: "13%"}, "申请入党日期"), 
                        React.createElement("td", {width: "13%"}, "思想汇报份数"), 
                        React.createElement("td", {width: "13%"}, "手机"), 
                        React.createElement("td", {width: "23%"}, "操作")), 
                    React.createElement("tr", null, 
                        React.createElement("td", null, 
                            React.createElement("input", {className: "lay-rad", name: "", type: "checkbox", value: ""})
                        ), 
                        React.createElement("td", null, 
                            React.createElement("span", {className: "cor_red"}, "丁皓")
                        ), 
                        React.createElement("td", null, "男"), 
                        React.createElement("td", null, "政企分公司"), 
                        React.createElement("td", null, "2011年2月"), 
                        React.createElement("td", null, "4"), 
                        React.createElement("td", null, "1300989900"), 
                        React.createElement("td", null, 
                            React.createElement("a", {className: "m2fm_abtn", href: "#"}, "编辑"), 
                            React.createElement("a", {className: "m2fm_abtn", href: "#"}, "转出"), 
                            React.createElement("a", {className: "m2fm_abtn", href: "#"}, "列为积极分子"))), 
                    React.createElement("tr", null, 
                        React.createElement("td", null, 
                            React.createElement("input", {className: "lay-rad", name: "", type: "checkbox", value: ""})
                        ), 
                        React.createElement("td", null, 
                            React.createElement("span", {className: "cor_red"}, "丁皓")
                        ), 
                        React.createElement("td", null, "男"), 
                        React.createElement("td", null, "政企分公司"), 
                        React.createElement("td", null, "2011年2月"), 
                        React.createElement("td", null, "4"), 
                        React.createElement("td", null, "1300989900"), 
                        React.createElement("td", null, 
                            React.createElement("a", {className: "m2fm_abtn", href: "#"}, "编辑"), 
                            React.createElement("a", {className: "m2fm_abtn", href: "#"}, "转出"), 
                            React.createElement("a", {className: "m2fm_abtn", href: "#"}, "列为积极分子"))), 
                    React.createElement("tr", null, 
                        React.createElement("td", null, 
                            React.createElement("input", {className: "lay-rad", name: "", type: "checkbox", value: ""})
                        ), 
                        React.createElement("td", null, 
                            React.createElement("span", {className: "cor_red"}, "丁皓")
                        ), 
                        React.createElement("td", null, "男"), 
                        React.createElement("td", null, "政企分公司"), 
                        React.createElement("td", null, "2011年2月"), 
                        React.createElement("td", null, "4"), 
                        React.createElement("td", null, "1300989900"), 
                        React.createElement("td", null, 
                            React.createElement("a", {className: "m2fm_abtn", href: "#"}, "编辑"), 
                            React.createElement("a", {className: "m2fm_abtn", href: "#"}, "转出"), 
                            React.createElement("a", {className: "m2fm_abtn", href: "#"}, "列为积极分子"))), 
                    React.createElement("tr", null, 
                        React.createElement("td", null, 
                            React.createElement("input", {className: "lay-rad", name: "", type: "checkbox", value: ""})
                        ), 
                        React.createElement("td", null, 
                            React.createElement("span", {className: "cor_red"}, "丁皓")
                        ), 
                        React.createElement("td", null, "男"), 
                        React.createElement("td", null, "政企分公司"), 
                        React.createElement("td", null, "2011年2月"), 
                        React.createElement("td", null, "4"), 
                        React.createElement("td", null, "1300989900"), 
                        React.createElement("td", null, 
                            React.createElement("a", {className: "m2fm_abtn", href: "#"}, "编辑"), 
                            React.createElement("a", {className: "m2fm_abtn", href: "#"}, "转出"), 
                            React.createElement("a", {className: "m2fm_abtn", href: "#"}, "列为积极分子"))), 
                    React.createElement("tr", null, 
                        React.createElement("td", null, 
                            React.createElement("input", {className: "lay-rad", name: "", type: "checkbox", value: ""})
                        ), 
                        React.createElement("td", null, 
                            React.createElement("span", {className: "cor_red"}, "丁皓")
                        ), 
                        React.createElement("td", null, "男"), 
                        React.createElement("td", null, "政企分公司"), 
                        React.createElement("td", null, "2011年2月"), 
                        React.createElement("td", null, "4"), 
                        React.createElement("td", null, "1300989900"), 
                        React.createElement("td", null, 
                            React.createElement("a", {className: "m2fm_abtn", href: "#"}, "编辑"), 
                            React.createElement("a", {className: "m2fm_abtn", href: "#"}, "转出"), 
                            React.createElement("a", {className: "m2fm_abtn", href: "#"}, "列为积极分子")))), 
                React.createElement("div", {className: "m2fm_page"}, 
                    React.createElement("a", {href: "#", className: "m2fmPage_a"}, "＜"), 
                    React.createElement("a", {href: "#", className: "m2fmPage_a on"}, "1"), 
                    React.createElement("a", {href: "#", className: "m2fmPage_a"}, "2"), 
                    React.createElement("a", {href: "#", className: "m2fmPage_a"}, "3"), 
                    React.createElement("a", {href: "#", className: "m2fmPage_a"}, "4"), 
                    React.createElement("a", {href: "#", className: "m2fmPage_a"}, "5"), 
                    React.createElement("a", {href: "#", className: "m2fmPage_a"}, "6"), 
                    React.createElement("a", {href: "#", className: "m2fmPage_a"}, "7"), 
                    React.createElement("span", {className: "m2fmPage_a2"}, "..."), 
                    React.createElement("a", {href: "#", className: "m2fmPage_a"}, "99"), 
                    React.createElement("a", {href: "#", className: "m2fmPage_a"}, "100"), 
                    React.createElement("a", {href: "#", className: "m2fmPage_a"}, "＞")))));
    }
}
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = MemberPage;
//# sourceMappingURL=membersPage.js.map